### ISSUE TITLE
Frame rate for Pupillometry

### ISSUE THREAD

**Issue by Phonetiker** [jeeliz/jeelizPupillometry#1]
Hello,
In the technical specifications of the camera module, a number of different frame-size-dependent frame rates are provided. Could you say what the raw frame rate is (before resampling) and whether user control of frame rate is possible/advisable in the Jeeliz Pupillometry setup?
Many thanks!

**Comment by xavierjs** [comment]
Hi @Phonetiker 

According to the specification of the camera module (http://www.elpcctv.com/8mp-highdefinition-usb-camera-module-usb20-sony-imx179-color-cmos-sensor-75degree-lens-p-223.html), the framerate is 15FPS (because we require a 8MP 3264X2448 video feed).

Then it also depends on the lighting. To get good results, the best is to adjust manually the lighting using v4l2ucp (https://github.com/jeeliz/jeelizPupillometry/blob/master/images/screenshots/v4l2ucp.png). If there is too few lighting, the camera will add motion blur, and the real framerate will be below the provided framerate. That's why I use a quite strong light.

But you also need a dedicated graphic card to run the app smoothly. With a weak GPU it may introduce a bottleneck. I tested it on my laptop with a GTX960M and on a Nvidia Jetson TX2 and it works fine. But with the lower GPU of my laptop (An intel HD something) is not enough.

The project has been a bit paused, mainly for funding issues. We have worked on an embedded version of the pupillometer using https://github.com/jeeliz/jetsonjs, but it is still in progress.

Best regards,
Xavier
