### ISSUE TITLE
Running jeelizPupillometry on a local host

### ISSUE THREAD

**Issue by Phonetiker** [jeeliz/jeelizPupillometry#2]
Hello,

My group has put together the pupillometry setup as described in the readme. We would like to run experiments locally, and so we would like to first run the demo locally. Two problems have come up:

1. Initially, running the experiment locally was causing an error because it does not use the right protocol:

jeelizPupillometry.js:19 Access to XMLHttpRequest at 'file:///Users/stobin/Downloads/jeelizPupillometry-master/dist/jeelizPupillometryNNC.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
     sa | @ | jeelizPupillometry.js:19

So I modified the file access options on launching the browser, which appears to have resolved that error:

> open /Applications/Google\ Chrome.app --args --allow-file-access-from-files

2. The second problem is that the video stream does not display in the Debug view, although the camera is active and is possible to use with other applications. This problem is proving more challenging to resolve, so I'd appreciate your input on it. Initially I'd assumed it was associated with the first problem, but those errors don't show up any more. However, when I run the demos remotely (those hosted on jeeliz.com) there's no problem with camera access and the experiment proceeds as expected.

Many thanks in advance.

**Comment by xavierjs** [comment]
Hi,

You need to run a local HTTPS server to serve the content. Otherwise there will be CORS errors and problems with camera access (i.e. you need to access to the content through https://127.0.0.1/<path>/index.html). See https://github.com/jeeliz/jeelizPupillometry#hosting

The lightweight Python https server included in https://github.com/jeeliz/jeelizFaceFilter, httpsServer.py (https://github.com/jeeliz/jeelizFaceFilter/blob/master/httpsServer.py) should do the job.
Put this script at the root of this repository, then start it as explained here: https://github.com/jeeliz/jeelizFaceFilter#the-development-server

To make loading faster, the webcam video stream and the neural network model are loaded asynchronously, that's why the webcam LED is active. But since the neural network model cannot be loaded because of the CORS problem the application does not start, and so the debug view is not displayed.
