### ISSUE TITLE
webcam specs

### ISSUE THREAD

**Issue by levexis** [jeeliz/jeelizPupillometry#4]
I found this computer cam for $50, is it sufficient?
https://www.aliexpress.com/item/8MP-USB-Webcam-CCTV-5-50mm-Varifocal-Lens-8Megapixel-High-Definition-Mini-HD-Security-Video-Camera/32992156524.html

**Comment by xavierjs** [comment]
Hi,

It seems good (8MP, good zoom level), but I m not sure.
If you try it, I would be very interested by your feedback (either here or by submitting a PR to edit the README.md).

Best,
Xavier

**Comment by levexis** [comment]
Sure, have ordered it and will submit a PR if I'm successful with it.

**Comment by levexis** [comment]
![FireShot Capture -  _ LIGHT INTENSITY PUPIL MEASUREMENT _ _ - https___127 0 0 1_levexis_jeelizPupi](https://user-images.githubusercontent.com/2098392/60509639-b9be5c80-9ccd-11e9-9d62-c7ce6bdc629a.png)

I think it is working, here is example output from the light intensity test. Great little camera it seems to me. Let me know if you want me to run any other tests.

**Comment by xavierjs** [comment]
Hi @levexis 

Thank you very much for your feedback.
What is the curve in the "Averaged results" tab ?
It should look like this one: https://github.com/jeeliz/jeelizPupillometry#light-intensity

The initial value is always 1, it is the pupil size at the beginning of each trial.
Then it should increase or decrease but not too abruptly.
If it is too abrupt, it may be due to a measurement problem.

Indeed, sometimes the tracking can be lost under some lighting conditions. For example if the screen is too bright, it can add a reflection point on the pupil which will disturb the measurement. It is important to check it in the "debug view" tab to see if the iris then the pupil are well segmented.

Best,
Xavier

**Comment by levexis** [comment]
I've been having a few problems so have a new graphics card coming for my PC. I get ok results but only for one eye and in debug mode it seems to be struggling. I never seem to get the red lines that I can see in the videos I've seen. If there is a good video/ article for getting going then please let me know. 

Thanks,

Paul

**Comment by xavierjs** [comment]
Hi @levexis 

The red lines are linked to the pupil detection.
In the debug view tab, they can be tweaked using the 2 first sliders (cf https://github.com/jeeliz/jeelizPupillometry#sliders-usage )
The first one should control their thickness and the second one their intensity.

The red lines are computed with edge detection.
So they depends a lot on the image quality around the pupil.
If it is a bit blurry (bad focus), it will be hard to detect edges.
Same if the image is too dark/too bright.
I had to tweak manually my camera settings because by default, the exposure is not set specifically for the eyes region but for the whole image. (on Linux, `v4l2ucp` then I put these settings: https://github.com/jeeliz/jeelizPupillometry/blob/master/images/screenshots/v4l2ucp.png )

For the graphic card, mine is a GTX960M.
I also tested it on Nvidia Jetson TX2 (about the same computing power than a GTX930M).

Best,
Xavier
