### ISSUE TITLE
How to get the pupil and iris radius

### ISSUE THREAD

**Issue by igors7** [jeeliz/jeelizPupillometry#6]
For educational purposes, we need to know the radius of the iris and pupil. How can we do this? We tried to look at the source code but found only the radius of the pupil there, how can we find the radius of the iris? Thanks!

**Comment by xavierjs** [comment]
Hi,

With a standard, uncalibrated camera, we cannot measure the radius of the pupil or the radius of the iris in exact units. There is always an unknown scale factor.

Internally, pupil and iris radius are computed in pixels of the camera image. But we never know the scale factor between pixel of the camera image at the pupil position and real-world units.

The only meaningful meaurement is the ratio between pupilRadius and irisRadius. This is what you can get from the lib.

Best,
Xavier

**Comment by igors7** [comment]
Hi,

I cannot find pupilRadius values in the code. Maybe this variable is denoted somehow differently?

Thanks,
Igor Sedov
Отправлено из приложения "Почта" для Windows 10

От: Bourry Xavier
Отправлено: 16 февраля 2020 г. в 3:16
Кому: jeeliz/jeelizPupillometry
Копия: igors7; Author
Тема: Re: [jeeliz/jeelizPupillometry] How to get the pupil and iris radius(#6)

Hi,
With a standard, uncalibrated camera, we cannot measure the radius of the pupil or the radius of the iris in exact units. There is always an unknown scale factor.
Internally, pupil and iris radius are computed in pixels of the camera image. But we never know the scale factor between pixel of the camera image at the pupil position and real-world units.
The only meaningful meaurement is the ratio between pupilRadius and irisRadius. This is what you can get from the lib.
Best,
Xavier

**Comment by xavierjs** [comment]
Hi,

I said that there is always an unknow scale factor. It means that we cannot get the pupil radius in absolute world unit (mm, inches or whatever).
We only have the ratio between the pupil radius and the iris radius. It is also a more robust measurement since people eyes size can vary. 
In this demo for example: https://github.com/jeeliz/jeelizPupillometry/blob/master/demos/lightIntensity/Experiment.js

pupil relative radi are given by `detectedState.pupilLeftRadius` and `detectedState.pupilRightRadius`
